# --- Build Stage ---
FROM maven:3.9.9-eclipse-temurin-26 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# --- Runtime Stage ---
FROM eclipse-temurin:26-jre
WORKDIR /app
# Copies the compiled jar generated by your Maven build phase
COPY --from=build /app/target/*.jar app.jar
EXPOSE 10000
# Runs the application using your specific Main class entry point
ENTRYPOINT ["java", "-cp", "app.jar", "io.github.placereporter99.utilitybot.Main"]