package io.github.placereporter99.utilitybot;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;

// Mostly generated by Google Gemini AI

public class DualOutputStream extends OutputStream {
    private final OutputStream targetOne;
    private final OutputStream targetTwo;

    public DualOutputStream(OutputStream targetOne, OutputStream targetTwo) {
        this.targetOne = targetOne;
        this.targetTwo = targetTwo;
    }

    public static PrintStream teeWithOut(OutputStream target) {
        return new PrintStream(new DualOutputStream(System.out, target));
    }

    public static PrintStream teeWithErr(OutputStream target) {
        return new PrintStream(new DualOutputStream(System.err, target));
    }

    @Override
    public void write(int b) throws IOException {
        // Write a single byte to both streams
        targetOne.write(b);
        targetTwo.write(b);
    }

    @Override
    public void write(byte[] b, int off, int len) throws IOException {
        // Write bulk bytes to both streams (optimized performance)
        targetOne.write(b, off, len);
        targetTwo.write(b, off, len);
    }

    @Override
    public void flush() throws IOException {
        targetOne.flush();
        targetTwo.flush();
    }

    @Override
    public void close() throws IOException {
        targetOne.close();
        targetTwo.close();
    }
}
